from cmd import (Package,
                 ShellCmd,
                 IfKeyword,
                 IfNotKeyword)


GLOBAL_USE_FLAGS = [
    'X', 'dga', 'dri', 'egl',
    'curl', 'ssl', 'gpm', 'dbus',
    'jit', 'threads', 'ncurses', 'elogind',
    'jpeg', 'png', 'bluetooth', 'pam',
    'python', 'alsa', 'opencl', 'inotify',
    'openmp', 'zstd', 'jumbo-build', 'asm',
    'device-mapper', 'gtk', 'vulkan', 'sdl',
    'osmesa', 'xinerama', 'v4l', 'opengl',
    'screencast',
    '-wayland', '-gnome', '-gnome-online-accounts', '-eds'
]


PACKAGES = [
    # earliest to emerge packages
    # other packages indirectly depend
    # on those
    Package('media-libs/libsndfile',
            use_flags='minimal',
            blocking=True),
    Package('net-misc/aria2',
            extra_use_flags='bittorent libuv ssh',
            blocking=True),
    Package('dev-util/vmtouch',
            blocking=True),

    Package('dev-util/ccache',
            keywords={'dev'}),

    # essential packages
    Package('sys-devel/gcc',
            use_flags='-* cet',
            extra_use_flags='jit graphite',
            blocking=True,
            keywords={'ram-hog'}),
    Package('app-shells/dash'),

    Package('sys-kernel/gentoo-kernel',
            binary_alternative='sys-kernel/gentoo-kernel-bin',
            use_flags='symlink',
            blocking=True),
    Package('sys-kernel/linux-firmware',
            use_flags='compress-xz deduplicate'),
    Package('sys-libs/ncurses',
            emerge_override='--nodeps',
            env={'USE': '-gpm'},
            blocking=True),
    Package('sys-libs/gpm',
            emerge_override='--nodeps',
            blocking=True),
    Package('sys-libs/ncurses',
            blocking=True),
    Package('sys-apps/portage',
            extra_use_flags='native-extensions ipc',
            blocking=True),


    Package('sys-apps/util-linux',
            use_flags='-logger'),
    Package('media-libs/libpng',
            use_flags='apng'),
    IfKeyword('minimal',
              Package('app-editors/vim',
                      use_flags='minimal'),
              Package('app-editors/vim',
                      extra_use_flags='perl lua python terminal')),

    Package('app-admin/sysklogd',
            use_flags='logger'),
    Package('sys-process/cronie'),

    Package('sys-boot/grub',
            use_flags='mount'),
    Package('sys-boot/os-prober'),
    Package('sys-apps/lm-sensors'),
    Package('sys-power/acpi'),
    Package('sys-process/procenv'),
    Package('dev-libs/light'),
    Package('app-arch/zip',
            use_flags='natspec'),
    Package('app-admin/pass',
            use_flags='git'),
    Package('app-admin/pass-otp'),
    Package('net-dialup/picocom'),
    Package('net-misc/networkmanager',
            use_flags='conncheck dhcpcd tools wifi',
            extra_use_flags='connection-sharing elogind iptables'),
    Package('net-wireless/iw'),
    Package('net-wireless/wireless-tools'),
    Package('net-wireless/wpa_supplicant',
            use_flags='ap'),
    Package('net-misc/proxychains'),
    Package('net-vpn/tor'),
    Package('net-dns/bind-tools'),
    Package('sys-apps/net-tools'),
    Package('net-proxy/mitmproxy'),
    Package('net-analyzer/tcpdump'),
    IfNotKeyword('minimal',
                 Package('net-proxy/privoxy',
                         use_flags=['compression',
                                    'fast-redirects',
                                    'whitelists',
                                    'threads',
                                    'extended-statistics']),
                 None
                 ),
    Package('net-misc/tigervnc',
            use_flags='server viewer',
            extra_use_flags='dri3 drm'),
    Package('sys-apps/mlocate'),
    Package('sys-fs/inotify-tools'),
    Package('sys-fs/e2fsprogs',
            use_flags='tools'),
    Package('sys-fs/exfatprogs'),
    Package('sys-fs/fuse-exfat'),
    Package('sys-fs/ntfs3g',
            use_flags='fuse mount-ntfs ntfsprogs'),
    Package('sys-fs/mtools'),
    Package('sys-fs/ncdu-bin'),
    Package('net-fs/sshfs'),
    Package('net-fs/samba'),
    Package('net-fs/cifs-utils'),
    Package('sys-fs/dosfstools'),
    Package('sys-fs/fuse-zip'),
    Package('sys-apps/smartmontools'),

    Package('dev-build/cmake',
            keywords={'dev'}),
    Package('dev-vcs/git',
            use_flags='webdav safe-directory',
            extra_use_flags='cgi gpg highlight',
            keywords={'dev'}),
    Package('dev-lang/python',
            use_flags='gdbm readline sqlite ncurses tk ssl',
            keywords={'dev'}),
    Package('dev-debug/gdb',
            use_flags='cet python server source-highlight',
            extra_use_flags='xml xxhash',
            keywords={'dev'}),
    Package('dev-util/android-tools',
            extra_use_flags='python',
            keywords={'dev'}),
    Package('dev-util/rr',
            keywords={'dev'}),
    Package('dev-dotnet/dotnet-sdk',
            binary_alternative='dev-dotnet/dotnet-sdk-bin',
            keywords={'dev'}),

    Package('dev-util/radare2',
            keywords={'dev'}),
    Package('dev-util/difftastic',
            keywords={'dev'}),
    Package('dev-debug/gef',
            keywords={'dev'}),
    Package('dev-debug/ltrace',
            extra_use_flags='elfutils',
            keywords={'dev'}),
    Package('dev-debug/strace',
            extra_use_flags='elfutils',
            keywords={'dev'}),
    IfNotKeyword('minimal',
                 Package('dev-util/valgrind',
                         keywords={'dev'}),
                 None),
    Package('app-misc/binwalk',
            keywords={'dev'}),
    Package('dev-util/cppcheck',
            keywords={'dev'}),
    Package('app-forensics/radamsa',
            keywords={'dev'}),
    IfNotKeyword('minimal',
                 Package('app-forensics/aflplusplus',
                         keywords={'dev'}),
                 None),
    Package('app-forensics/zzuf',
            keywords={'dev'}),
    Package('dev-util/poke',
            use_flags='nbd',
            keywords={'dev'}),
    Package('dev-util/bear',
            keywords={'dev'}),
    Package('media-gfx/graphviz',
            keywords={'dev'}),
    Package('app-misc/hivex',
            use_flags='perl'),


    IfNotKeyword('minimal',
                 Package('media-fonts/fira-code'),
                 None),

    Package('dev-util/glslang'),  # for mesa build
    Package('media-libs/mesa',
            use_flags='d3d9 lm-sensors vdpau'),
    Package('media-libs/libpulse',
            use_flags='glib'),
    Package('media-sound/alsa-utils',
            use_flags='bat ncurses'),
    Package('media-libs/libmpd'),

    Package('app-arch/unrar'),
    Package('sys-apps/lshw'),
    Package('app-containers/docker'),
    Package('app-containers/docker-cli'),
    Package('app-containers/docker-compose'),

    Package('app-emulation/qemu',
            use_flags=['aio', 'alsa', 'capstone', 'fdt',
                       'fuse', 'io-uring', 'iscisi', 'plugins',
                       'sdl-image', 'vnc', 'vhost-net',
                       'spice', 'ssh', 'usb', 'usbredir',
                       'QEMU_USER_TARGETS_AARCH64',
                       'QEMU_USER_TARGETS_x86_64']),
    Package('app-emulation/wine-staging',
            use_flags=['dos', 'gecko', 'faudio',
                       'mono', 'udev', 'run-exes',
                       'netapi', 'samba', 'mingw']),
    Package('app-emulation/winetricks'),

    Package('media-gfx/imagemagick',
            use_flags=['djvu', 'lzma', 'postscript',
                       'raw', 'svg', 'webp']),

    Package('www-client/links',
            use_flags=['freetype', 'libevent', 'ipv6',
                       'lzma', 'tiff', 'fbcon']),

    Package('app-admin/doas'),
    Package('sys-apps/inxi'),
    Package('app-misc/jq'),
    Package('app-misc/yq'),

    IfNotKeyword('minimal',
                 Package('media-gfx/freecad',
                         use_flags=['addonmgr', 'designer', 'fem',
                                    'gui', 'image', 'inspection',
                                    'material', 'netgen', 'part-design',
                                    'show', 'surface', 'techdraw',
                                    'openscad', 'raytracing']),
                 None),

    Package('media-gfx/openscad',
            use_flags='gui'),
    Package('net-print/hplip', use_flags='hpcups'),
    Package('app-eselect/eselect-repository'),

    Package('app-shells/fish'),
    Package('app-text/tree'),

    Package('app-shells/fzf'),
    Package('app-misc/tmux'),
    IfNotKeyword('minimal',
                 Package('sys-apps/ripgrep-all'),
                 None),
    Package('sys-process/htop'),

    Package('x11-base/xorg-server',
            use_flags='xephyr xorg xvfb'),
    Package('x11-apps/setxkbmap'),
    Package('x11-apps/xrandr'),
    Package('x11-apps/xev'),
    Package('x11-misc/xdo'),
    Package('x11-misc/xdotool'),
    Package('x11-misc/xfe'),
    Package('x11-apps/xkill'),

    ShellCmd('git clone --depth=1 https://github.com/rvaiya/warpd.git'
             ' && cd warpd; DISABLE_WAYLAND=1 make && make install; cd -',
             ' && rm -rf warpd',
             name='warpd installation'),

    Package('media-gfx/scrot'),
    Package('x11-misc/clipmenu',
            use_flags='rofi -dmenu'),

    Package('x11-wm/bspwm'),
    Package('x11-misc/sxhkd'),

    Package('x11-misc/picom',
            use_flags='config-file drm'),
    Package('x11-misc/polybar',
            use_flags='mpd network ipc'),
    Package('x11-misc/rofi'),
    Package('x11-misc/xclip'),
    Package('x11-apps/xdpyinfo'),


    ########
    IfNotKeyword('minimal',
                 Package('app-emulation/libvirt',
                         use_flags='libssh lvm parted qemu libvirtd'),
                 None),
    IfNotKeyword('minimal',
                 Package('app-emulation/virt-manager',
                         use_flags='gui'),
                 None),

    Package('www-client/firefox',
            binary_alternative='www-client/firefox-bin',
            use_flags=['system-harfbuzz', 'system-icu', 'system-jpeg',
                       'system-libevent', 'system-png', 'system-python-libs',
                       'system-webp', 'geckodriver', 'openh254'],
            keywords={'ram-hog'}),
    Package('app-office/libreoffice',
            binary_alternative='app-office/libreoffice-bin',
            use_flags='pdfimport',
            keywords={'ram-hog'}),

    Package('net-im/telegram-desktop',
            binary_alternative='net-im/telegram-desktop-bin'),

    Package('media-gfx/feh'),
    IfNotKeyword('minimal',
                 Package('media-gfx/gimp',
                         use_flags='webp lua'),
                 None),

    Package('media-gfx/flameshot'),
    Package('media-video/peek'),
    IfNotKeyword('minimal',
                 Package('app-admin/conky',
                         use_flags='intel-backlight iostats portmon imlib rss'),
                 None),
    Package('x11-terms/st',
            use_flags='savedconfig'),
]
